apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: repo-operator
  name: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: repo-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: repo-operator
spec:
  selector:
    matchLabels:
      control-plane: repo-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: repo-operator
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: repo-operator:latest
          imagePullPolicy: IfNotPresent
          name: repo-operator
          env:
          - name: OPERATOR_NAME
            value: repo-operator
          - name: REPOSITORY_URL
            valueFrom:
              secretKeyRef:
                name: repo-operator-repo-secret
                key: url
          - name: REPOSITORY_USERNAME
            valueFrom:
              secretKeyRef:
                name: repo-operator-repo-secret
                key: username
          - name: REPOSITORY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: repo-operator-repo-secret
                key: password
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: repo-operator
      serviceAccountName: repo-operator
      terminationGracePeriodSeconds: 30