apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    name: repo-operator
  name: repo-operator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: repo-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: repo-operator
    spec:
      containers:
        -
          env:
            - name: REPOSITORY_URL
              value: 'https://<your-artifactory-server-url>/artifactory'
            - name: REPOSITORY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: repository-secret
                  key: username
            - name: REPOSITORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: repository-secret
                  key: password
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: repo-operator
          image: <path-of-repo-operator-image>:<tag>
          imagePullPolicy: Always
          name: repo-operator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: repo-operator
      serviceAccountName: repo-operator
      terminationGracePeriodSeconds: 30